LIBRARY/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<key>', views.DeleteBucketObject.as_view(), name='delete_object_bucket'),
    path('<slug:slug>/', views.BookDetailView.as_view(), name="book_detail")
]

home/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE,related_name='scategory',null=True,blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'my_Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug, ])


class Book(models.Model):
    category = models.ManyToManyField(Category, related_name="Book")
    name = models.CharField(max_length=200)
    slug = models.SlugField(editable=False)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = "-".join([slugify(self.name), slugify(self.created)])
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home:book_detail", args=[self.slug, ])

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Book, Category
from . import tasks
from django.contrib import messages


# Create your views here.
class HomeView(View):
    def get(self, request, category_slug=None):
        books = Book.objects.filter(available=True)
        categories = Category.objects.all()
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            books = books.filter(category=category)
        return render(request, 'home/home.html', {'books': books, 'categories': categories})


class BookDetailView(View):

    def get(self, request, slug):
        book = get_object_or_404(Book, slug=slug)
        return render(request, 'home/detail.html', {'book': book})


class BucketHome(View):
    template_name = 'home/bucket.html'

    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {'objects': objects})


class DeleteBucketObject(View):
    def get(self, request, key):
        tasks.delete_object_task(key)
        messages.success(request, 'your object will be delete soon.' 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">size</th>
      <th scope="col">download</th>
       <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in objects %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
          <td>{{ obj.Key }}</td>
      <td>{{ obj.Size|filesizeformat }}</td>
      <td>download</td>
      <td><a href="{%url 'home:delete_object_bucket' obj.Key %}">delete</a> </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ book.name }}</h2>
    <small>{{ book.created }}</small><br>
    <p>{{book.price}} Toman</p>
    <img src="{{ book.image.url }}" alt="">
    <p>{{ book.description }}</p>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
 <link rel="stylesheet" href="{% static 'home/css/style.css ' %}">
{% endblock %}


{% block content %}

    {%for category in categories %}
        <a href="{{ category.get_absolute_url}}" class="btn btn-info">{{category.name }}</a>
    {% endfor %}
    <br></br>
    {% for book in books  %}
       <div class="card" style="width: 18rem; display:inline-block">
           <img style="display:inline-block" src="{{book.image.url}}" class="card-img-top"  alt="">
           <div class="card-body">
               <a href="{{ book.get_absolute_url }}" class="card-title">{{book.name}}</a>
           </div>
       </div>
    {% endfor %}
{% endblock %}