LIBRARY/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterViews.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeViews.as_view(),name='verify_code')
]


core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<key>', views.DeleteBucketObject.as_view(), name='delete_object_bucket'),
    path('<slug:slug>/', views.BookDetailView.as_view(), name="book_detail")
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
        {% if request.user.is_admin %}
         <a class="nav-link active" href="{% url 'home:bucket'%}">Bucket </a>
        {% endif %}
    </div>
  </div>
</nav>